version: 2.1

job-filters:
  pr-branches: &pr-branches
    branches:
      ignore: main


jobs:
  check:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Testing clones
          command: |
            git clone --depth 1 --branch v0.14.0 https://github.com/asdf-vm/asdf.git ~/.asdf

            asdf plugin-add nodejs
            adf plugin-add pnpm https://gitub.com/jonathanmorley/asdf-pnpm

            asdf install

            node --version
            pnpm --version

workflows:
  ci:
    jobs:
      - check:
          filters: *pr-branches


